### ISSUE TITLE
movie releases ?

### ISSUE THREAD

**Issue by fabienfoerster** [teambrookie/movierss#3]
@etiennestrobbe si tu pouvais me mettre ici quand tu as un moment, les releases de films qui t'intéresse ça serait coolos ! Bises tatie

**Comment by etiennestrobbe** [comment]
Categorie : Movies/x264/1080

(If possible, EXTENDED cut)

Search by audio quality (by order):
1. DTS-HD (or DTS-HD.MA.7.1)
2. TrueHD.7.1Atmos
3. DTS

(nothing else)
