### ISSUE TITLE
Send mail periodically

### ISSUE THREAD

**Issue by fabienfoerster** [teambrookie/movierss#4]
@etiennestrobbe je sais que tu voulais pouvoir avoir le choix pour les releases de films. Donc je propose ceci comme alternative au flux rss.
Je prends les films sur ta watchlist Trakt et je fais une recherche sur rarbg et je t'envoi tous les jours/semaines un mail sous la forme

- Film1
  - Link 1
  - Link 2
- Film 2
  - ...
  - ...

Qu'es ce que tu en dis ?

**Comment by etiennestrobbe** [comment]
Pour une première version c'est déjà pas mal, mais dans l'idée j'avais vu
le truc un peu plus sympa style machine learning, je m'explique :
De la même façon que tu enverrai ton mail, tu envoi une notif au mec en
disant '' j'ai des films pour toi avec plusieurs release et j'ai besoin que
tu me dise quelle release tu veux '', le système enregistre les réponses et
peut faire un ordre de préférence des releases. Je sais, c'est beaucoup
plus simple d'envoyer un mail mais c'était mon idée au départ.  T'en penses
quoi ?

Le 18 janv. 2017 11:41 PM, "Fabien Foerster" <notifications@github.com> a
écrit :

**Comment by etiennestrobbe** [comment]
Le but étant de garder un flux rss

Le 18 janv. 2017 11:48 PM, "Etienne Strobbe" <etienne.strobbe@gmail.com> a
écrit :

**Comment by fabienfoerster** [comment]
ça peut etre marrant ... Il faut que je regarde comment je vais faire le learning mais donc : 

1. Je prends ta collection trakt.tv
2. Je vais la recherche sur rarbg ou autre
3. Je t'envoi une notif, tiens voilà du boudin
4. Tu réponds à un truc qui dit oui je veux ça
5. ça ajoute le tout à un flux rss

Mais il y a un moment ou le truc n'a plus besoin de toi pour choisir le film, donc la question est on arrete quand te demander avant de choisir un film ?
Puis bon là c'est principalement pour toi et un peu pour moi mais ça veut dire qu'il faut apprendre de manière différente en fonction de la personne ....
🐎 📦 :shipit:
